version: '3'
services:
  colornet:
    container_name: colornet
    restart: unless-stopped
    command: "/bin/bash"
    stdin_open: true
    working_dir: '/colornet'
    tty: true
    # image: tensorflow/tensorflow:0.8.0
    image: tensorflow/tensorflow:0.8.0-devel-gpu
    # environment:
    #   test: ""
    volumes:
      - ./:/colornet
    # ports:
    #   - "8888:8888"

